package com.pranavkd.instadown.presentation.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF172839)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF2D3E50)
val OnPrimaryContainer = Color(0xFF97A9BE)
val PrimaryFixed = Color(0xFFD2E4FB)
val OnPrimaryFixed = Color(0xFF0A1D2D)
val PrimaryFixedDim = Color(0xFFB6C8DF)
val OnPrimaryFixedVariant = Color(0xFF37485B)
val InversePrimary = Color(0xFFB6C8DF)

val Secondary = Color(0xFF775A19)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFFED488)
val OnSecondaryContainer = Color(0xFF785A1A)
val SecondaryFixed = Color(0xFFFFDEA5)
val OnSecondaryFixed = Color(0xFF261900)
val SecondaryFixedDim = Color(0xFFE9C176)
val OnSecondaryFixedVariant = Color(0xFF5D4201)

val Tertiary = Color(0xFF352408)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF4D391C)
val OnTertiaryContainer = Color(0xFFBFA37E)
val TertiaryFixed = Color(0xFFFEDDB5)
val OnTertiaryFixed = Color(0xFF281801)
val TertiaryFixedDim = Color(0xFFE0C29B)
val OnTertiaryFixedVariant = Color(0xFF584325)

val Background = Color(0xFFFCF9F8)
val OnBackground = Color(0xFF1C1B1B)
val Surface = Color(0xFFFCF9F8)
val OnSurface = Color(0xFF1C1B1B)
val SurfaceDim = Color(0xFFDCD9D9)
val SurfaceBright = Color(0xFFFCF9F8)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF6F3F2)
val SurfaceContainer = Color(0xFFF0EDEC)
val SurfaceContainerHigh = Color(0xFFEBE7E7)
val SurfaceContainerHighest = Color(0xFFE5E2E1)
val SurfaceVariant = Color(0xFFE5E2E1)
val OnSurfaceVariant = Color(0xFF43474C)
val InverseSurface = Color(0xFF313030)
val InverseOnSurface = Color(0xFFF3F0EF)
val Outline = Color(0xFF74777D)
val OutlineVariant = Color(0xFFC4C6CD)
val SurfaceTint = Color(0xFF4F6073)

val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)
